GET http://localhost:5154/users

###
GET http://localhost:5154/users/16

###
POST http://localhost:5154/auth/register
Content-Type: application/json

{
    "username": "testuser",
    "email": "test@mail.com",
    "password": "gigelpass"
}

###
POST http://localhost:5154/auth/login
Content-Type: application/json

{
    "username": "gigel",
    "password": "gigelpass"
}